default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: 1000book-development
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: 1000book-test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>


